services:
  api1:
    image: testapi
    build:
      context: .
      dockerfile: src/TestApi/Dockerfile
  
  api2:
    image: testapi
    build:
      context: .
      dockerfile: src/TestApi/Dockerfile
  
  api3:
    image: testapi
    build:
      context: .
      dockerfile: src/TestApi/Dockerfile
  
  nginx:
    image: nginx
    links:
      - api1:api1
      - api2:api2
      - api3:api3
    ports:
      - "5100:5100"
    volumes:
      - ./proxy.conf:/etc/nginx/proxy.conf
      - ./nginx.conf:/etc/nginx/nginx.conf